spring:
  redis:
    host: 123.56.169.57
    port: 6379
    password: weimin
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数
        max-active: 1024
        max-idle: 200
        max-wait: 10000ms
        min-idle: 5